Update glium versions
The samples were crashing on Windows with `thread 'main' panicked at 'gl function was not loaded'`.

Most likely due to: https://github.com/glium/glium/issues/1648